apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: canary-demo
  name: canary-demo
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary-demo
  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
      - image: quay.io/andrleite/rollouts-demo:blue
        imagePullPolicy: Always
        name: canary-demo
        env:
          - name: CANARY
            valueFrom:
              secretKeyRef:
                name: canary
                key: canary
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: canary
type: Opaque
data:
  canary: dHJ1ZQ==
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: canary-demo
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 99
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: canary-demo
---
apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: canary-demo
  namespace: canary-demo
spec:
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: canary-demo
  canaryAnalysis:
    webhooks:
      # - name: "ask for confirmation"
      #   type: confirm-rollout
      #   url: http://flagger-loadtester.canary-demo/gate/check
      # - name: "promotion gate"
      #   type: confirm-promotion
      #   url: http://flagger-loadtester.canary-demo/gate/approve
    interval: 30s
    iterations: 5
    threshold: 3
    maxWeight: 50
    stepWeight: 10
    #canary match condition
    # match:
    #   - headers:
    #       x-version:
    #         exact: PR-42
    metrics:
    - interval: 1m
      name: request-success-rate
      threshold: 99
    - interval: 30s
      name: request-duration
      threshold: 500
  progressDeadlineSeconds: 30
  provider: istio
  service:
    gateways:
    - mesh
    hosts:
    - canary.demo
    port: 9898
    portDiscovery: false
    portName: http
    targetPort: http
  skipAnalysis: false
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: canary-demo
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mesh
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - canary.demo
    port:
      name: http
      number: 80
      protocol: HTTP
