apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-test
  name: api-test
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: api-test
  template:
    metadata:
      labels:
        app: api-test
    spec:
      containers:
      - image: quay.io/andrleite/rollouts-demo:green
        imagePullPolicy: Always
        name: api-test
        env:
          - name: CANARY
            valueFrom:
              secretKeyRef:
                name: api-test
                key: canary
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: api-test
type: Opaque
data:
  canary: dHJ1ZQ==
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: api-test
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 99
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-test
---
apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: api-test
  namespace: api-test
spec:
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: api-test
  canaryAnalysis:
    webhooks:
      # - name: "ask for confirmation"
      #   type: confirm-rollout
      #   url: http://flagger-loadtester.canary-demo/gate/check
      # - name: "promotion gate"
        type: confirm-promotion
        url: http://flagger-loadtester.canary-demo/gate/halt
    interval: 1m
    threshold: 3
    maxWeight: 50
    stepWeight: 10
    #canary match condition
    iterations: 3
    match:
      - headers:
          x-version:
            exact: PR-42
    metrics:
    - interval: 1m
      name: request-success-rate
      threshold: 99
    - interval: 30s
      name: request-duration
      threshold: 500
  progressDeadlineSeconds: 30
  provider: istio
  service:
    gateways:
    - mesh
    hosts:
    - api-test.pismo.lab
    port: 9898
    portDiscovery: false
    portName: http
    targetPort: http
  skipAnalysis: false
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-test
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mesh
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - api-test.pismo.lab
    port:
      name: http
      number: 80
      protocol: HTTP
